### ISSUE TITLE
Support regex

### ISSUE THREAD

**Issue by connorjclark** [JZomDev/zom-external-plugins#15]
It'd be nice to support pattern matching. Ex: `Burnt.*` would match `Burnt fish` and `Burnt shrimp`.

since `,` is the separator and is also a valid regex value, simplest way would be to support a subset of regex (just split string by comma and parse all all regexes). nbd if comma isn't allowed in regex.

Might need a checkbox to toggle this feature otherwise non-technical users might get confused by item names with parentheses.

**Comment by JoshPaulie** [comment]
This would be incredbile.
