### ISSUE TITLE
Suggestion: Absorption potion notification

### ISSUE THREAD

**Issue by JoshPaulie** [JZomDev/zom-external-plugins#16]
Absorption potion notification would be useful for your NMZ plugin. It's great, by the way.

**Comment by JZomDev** [comment]
The Idle Notify plugin does this already.

**Comment by JoshPaulie** [comment]
Oh, okay thanks. I doesn't specify that in the settings.

**Comment by JZomDev** [comment]
Oh sorry, idle notifier doesn't do it but the built in NMZ plugin does it.
