### ISSUE TITLE
Items missing after closing and opening runelite after system update

### ISSUE THREAD

**Issue by Mortilol** [JZomDev/zom-external-plugins#17]
After a system update runelite forces you to close and reopen runelite. When I do this the items I have listed to drop are missing. There is none listed anymore. It's not that big of a deal but I've been having same problem with some other external pluggins where things are missing after system update. Yes I am logged into my runelite acc at all times. Any idea why this is happening and how to fix?

**Comment by JZomDev** [comment]
Seems like an issue with runelite itself or writing permissions for it. Please use the runelite discord for support. Feel free to @zom there
