### ISSUE TITLE
Interaction with Menu Swapper Extended plugin

### ISSUE THREAD

**Issue by joeamansfield** [JZomDev/zom-external-plugins#19]
For some reason, this plugin seems to interact with the Menu Swapper Extended plugin that is on the hub. When you enable one of them, both are enabled, and the same applies to disabling them. This is pretty annoying, since I would like to leave menu swapper on all the time, but only enable this when I am actually using it.

**Comment by joeamansfield** [comment]
raiyni who does menu swapper extended fixed it

**Comment by JZomDev** [comment]
i fixed it. https://github.com/runelite/plugin-hub/pull/2307
