### ISSUE TITLE
Item Separation?

### ISSUE THREAD

**Issue by ymaerc** [JZomDev/zom-external-plugins#2]
Hey, how is the list organized? I've added a bunch of items since wildcarding doesn't seem to work, but since adding them all, it doesn't filter them, only the first item in the list left click drops.
I've tried comma separation and breaks, and both combined.

**Comment by JZomerlei** [comment]
You must use entire item names. 
The list is item1,item2,item3 with no spaces inbetween the items. 

Ie: “raw salmon,raw trout”

Wild characters are currently not supported.

**Comment by hawkins** [comment]
Would it be feasible to allow separation by line breaks? I've got lots of items in my list (lots of fish, ores, seeds etc), and splitting them by lines would help me read them at a glance to keep them organized. Happy to PR it if need be

**Comment by redrumze** [comment]
Go ahead and PR it. @hawkins

**Comment by hawkins** [comment]
Thanks to #18 and @JZomDev , looks like this can be closed again now. Thanks!
