### ISSUE TITLE
Left click drop no longer works.

### ISSUE THREAD

**Issue by netstormuk** [JZomDev/zom-external-plugins#20]

**Comment by er-ck** [comment]
Just came to check if anyone reported this and yep. It's no longer working. Is this a move by Jagex or Runelite? Or just a bug?

**Comment by er-ck** [comment]
Just read the latest update about the inventory rework. Turns out this plugins purpose is built into the official Jagex client now, if you right click your inventory icon there's a "Configure Left-click" option that works exactly like this plugin.

**Comment by netstormuk** [comment]
> Just read the latest update about the inventory rework. Turns out this plugins purpose is built into the official Jagex client now, if you right click your inventory icon there's a "Configure Left-click" option that works exactly like this plugin.

Is this something Runelite will need to change for their client?

When I right click on the inventory button it just has the options of Inventory and Cancel.

**Comment by er-ck** [comment]
Turns out I had a different plugin that's still working, Menu Entry Swapper under item swaps there's a "Customizable left-click".
Thought the new anti-drag features mentioned in the update was the reason I was getting that option, oops my bad :skull:

**Comment by netstormuk** [comment]
> Turns out I had a different plugin that's still working, Menu Entry Swapper under item swaps there's a "Customizable left-click". Thought the new anti-drag features mentioned in the update was the reason I was getting that option, oops my bad 💀

Ah thank you, that plugin works.
