### ISSUE TITLE
AFK gotr

### ISSUE THREAD

**Issue by pettrs** [JZomDev/zom-external-plugins#22]
can you add the ability to be able to opt out of being pinged when to start mining, and only be pinged when to stop mining?

also, not sure if it's just me, but the info box isn't appearing.

**Comment by JZomDev** [comment]
Yeah, the info box is fixed for next release.

I can enable that notify too.

**Comment by JZomDev** [comment]
Done https://github.com/JZomDev/zom-external-plugins/tree/zom-afk-gotr-1.1
