### ISSUE TITLE
AFK GOTR

### ISSUE THREAD

**Issue by pettrs** [JZomDev/zom-external-plugins#23]
Possibly add notifications on portal spawns until you've reached 150 points.

currently, when you AFK, you turn off the plugin so it doesn't ping you while you're AFKing. having the notifications work until you've reached the point cap could be really helpful

**Comment by cwhitehead-kabam** [comment]
@JZomDev I'd like to have this as well. Are you accepting PRs? I can add this myself if you'd rather not.

**Comment by whiitehead** [comment]
@JZomDev I'd like this as well. Are you accepting PRs?

**Comment by JZomDev** [comment]
@whiitehead go ahead. Feel free to @ me on runelite discord to collaborate too if you want to. @redrumze there.
