### ISSUE TITLE
Suggestion for Slash Swapper

### ISSUE THREAD

**Issue by vitorebom** [JZomDev/zom-external-plugins#24]
Is it possible to have a checkbox to use the Swapper logic for Guest Clan Chat instead?  
So the plugin would look like this:

**Checkbox off**
- / is CC
- // is FC
- /// is GC
**Checkbox ON**
- / is GC
- // is FC
- /// is CC

**Comment by JZomDev** [comment]
> Is it possible to have a checkbox to use the Swapper logic for Guest Clan Chat instead?  
> 
> So the plugin would look like this:
> 
> 
> 
> **Checkbox off**
> 
> - / is CC
> 
> - // is FC
> 
> - /// is GC
> 
> **Checkbox ON**
> 
> - / is GC
> 
> - // is FC
> 
> - /// is CC
> 
> 

It is possible, I could look into doing this. Not quite sure how many people are using GC so I wasn't aware.

**Comment by JZomDev** [comment]
This is finally done in https://github.com/JZomDev/zom-external-plugins/commit/610f88550d0b279865a230b1c645bb8f3144ffe0
