### ISSUE TITLE
AFK GOTR Rune Notification Toggle

### ISSUE THREAD

**Issue by JPFlare** [JZomDev/zom-external-plugins#25]
It would be super helpful to allow the plugin to notify you when a specific rune is in the rotation -- when playing on an Iron I find myself wanting to afk until a specific rune shows up, rather than going for death/fire/blood specifically.

**Comment by JZomDev** [comment]
> It would be super helpful to allow the plugin to notify you when a specific rune is in the rotation -- when playing on an Iron I find myself wanting to afk until a specific rune shows up, rather than going for death/fire/blood specifically.

Consider it done mr iron.

**Comment by JZomDev** [comment]
Added in 1.3

**Comment by JPFlare** [comment]
Any idea when it will make it to the plugin hub on runelite?

**Comment by JZomDev** [comment]
It will be added when ever the team that approves them gets around to it. 

I have no clue when that might be. 

For more just ping me on discord.
