### ISSUE TITLE
Dense Runestone - Highlight not working

### ISSUE THREAD

**Issue by dstammen** [JZomDev/zom-external-plugins#33]
Ever since the highlight altars was added, the dense runestones when runecrafting bloods stop working when you walk away and come back. In order to fix, you have to disable and re-enable the plugin but it does the same thing when you walk away again.

**Comment by JZomDev** [comment]
I'm aware haven't had time to take a look at it, I'll fix it on the 17th when I'm home from vacation. 

I didn't test it thoroughly whoops.

**Comment by JZomDev** [comment]
Fixed.
