### ISSUE TITLE
[Combat Level Muting] Overhead hiding doesn't work when RuneLite's Chat Filter is enabled.

### ISSUE THREAD

**Issue by Dann37** [JZomDev/zom-external-plugins#35]
Title.

**Comment by JZomDev** [comment]
I cannot recreate this issue, if you have people added on your friends list they bypass the chat filter plugin but still not bypass by combat level muting.

**Comment by JZomDev** [comment]
This is fixed in https://github.com/runelite/plugin-hub/pull/5507

**Comment by Dann37** [comment]
My hero!
Thanks for the quick fix. 👍
