### ISSUE TITLE
Most recent update broke slash sweeper

### ISSUE THREAD

**Issue by Stickaplex** [JZomDev/zom-external-plugins#36]
At least for me. Just doesn't work currently

**Comment by JZomDev** [comment]
It seems to work fine for me.

/ -> clan chat
// -> friends chat

if you enable "Swap Guest Chat" it will behave different and send to guest chat on / and // on friends chat

**Comment by Stickaplex** [comment]
yea dunno what happened but i rebooted rl/reinstalled and seems to work fine now. dunno what was up
