### ISSUE TITLE
Certain items are not being affected by the plugin

### ISSUE THREAD

**Issue by technicbuff** [JZomDev/zom-external-plugins#37]
Hello,

I currently have the following items listed in my left click drop list (I have double checked the spelling) but they still do not have drop as their left click option:

iron dagger
cowhide
papaya

**Comment by JZomDev** [comment]
Are you sure you aren't having the normal menu entry swapper not undo your swap? 

@redrumze on runelite's discord from the #general chat and I can provide maybe better support.

**Comment by technicbuff** [comment]
okay, i'll post there
